### ISSUE TITLE
can you release a version?

### ISSUE THREAD

**Issue by AllenX2018** [uber-go/ratelimit#55]
Hello ~ community maintainer:
the community has not released a version for a long time, can you release a version?

**Comment by rabbbit** [comment]
We haven't released a new version for a long time because not a lot of external functionality has changed in a long time.

We'll release a new 0.X version in a couple of weeks - there's a slack bug we'd like to fix first. In the meantime please use `go get go.uber.com@4fc173c9d3c468c7237a9d7616017378e342bb35`

**Comment by AllenX2018** [comment]
Thank you

**Comment by rabbbit** [comment]
0.2.0 is now released.
